; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:uno_r4_wifi]
platform = renesas-ra
framework = arduino
board = uno_r4_wifi
lib_deps = 
    ${sysenv.USERPROFILE}\Documents\doc-lab\ICS_Library_for_Arduino_V3_0\IcsClass_V300.zip
    https://github.com/lipoyang/ICSlib.git